FROM apache/tika:latest-full
USER root
RUN set -eux \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
       tesseract-ocr-chi-sim \
       tesseract-ocr-chi-tra \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
USER 35002:35002
EXPOSE 9998
